create table company (apiId bigint, id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table game (rating float(53), release_year integer, apiid bigint, id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table game_companies (Game_id bigint not null, companies_id bigint not null) engine=InnoDB;
create table game_genres (Game_id bigint not null, genres_id bigint not null) engine=InnoDB;
create table game_platforms (Game_id bigint not null, platforms_id bigint not null) engine=InnoDB;
create table game_themes (Game_id bigint not null, themes_id bigint not null) engine=InnoDB;
create table genre (apiId bigint, id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table platform (apiId bigint, id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table theme (apiId bigint, id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
alter table company add constraint UKlkvfysmm15dt0rc1706ffvsr0 unique (apiId);
alter table game add constraint UKmdhud60uv9rejgpn1c22bdkd4 unique (apiid);
alter table genre add constraint UK7l2t2mtkdkuugpi2d0kp79jwy unique (apiId);
alter table platform add constraint UK4jl2m11bbmlabi4x7o50361w3 unique (apiId);
alter table theme add constraint UK7booc8h7biol5ahmcxg1wkhru unique (apiId);
alter table game_companies add constraint FK6mp20inlbc6jc8axef8tupq41 foreign key (companies_id) references company (id);
alter table game_companies add constraint FKl6bop2qxxfspoi00fd548hlk5 foreign key (Game_id) references game (id);
alter table game_genres add constraint FKw91cn6ww8yw72nr59y28i8me foreign key (genres_id) references genre (id);
alter table game_genres add constraint FK5tttono3swnbiopye7o19x0ur foreign key (Game_id) references game (id);
alter table game_platforms add constraint FKeqvfcfahkc1l3qnvpo78wjhsr foreign key (platforms_id) references platform (id);
alter table game_platforms add constraint FKi0s0wfmp3p34xfm3h9458cmcx foreign key (Game_id) references game (id);
alter table game_themes add constraint FKivce915we1ihempqv946jng1v foreign key (themes_id) references theme (id);
alter table game_themes add constraint FKo0td1ul31p4jopy8wtlbg5rhb foreign key (Game_id) references game (id);
create table company (apiId bigint, id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table game (rating float(53), release_year integer, apiid bigint, id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table game_companies (Game_id bigint not null, companies_id bigint not null) engine=InnoDB;
create table game_genres (Game_id bigint not null, genres_id bigint not null) engine=InnoDB;
create table game_platforms (Game_id bigint not null, platforms_id bigint not null) engine=InnoDB;
create table game_themes (Game_id bigint not null, themes_id bigint not null) engine=InnoDB;
create table genre (apiId bigint, id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table platform (apiId bigint, id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table theme (apiId bigint, id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
alter table company add constraint UKlkvfysmm15dt0rc1706ffvsr0 unique (apiId);
alter table game add constraint UKmdhud60uv9rejgpn1c22bdkd4 unique (apiid);
alter table genre add constraint UK7l2t2mtkdkuugpi2d0kp79jwy unique (apiId);
alter table platform add constraint UK4jl2m11bbmlabi4x7o50361w3 unique (apiId);
alter table theme add constraint UK7booc8h7biol5ahmcxg1wkhru unique (apiId);
alter table game_companies add constraint FK6mp20inlbc6jc8axef8tupq41 foreign key (companies_id) references company (id);
alter table game_companies add constraint FKl6bop2qxxfspoi00fd548hlk5 foreign key (Game_id) references game (id);
alter table game_genres add constraint FKw91cn6ww8yw72nr59y28i8me foreign key (genres_id) references genre (id);
alter table game_genres add constraint FK5tttono3swnbiopye7o19x0ur foreign key (Game_id) references game (id);
alter table game_platforms add constraint FKeqvfcfahkc1l3qnvpo78wjhsr foreign key (platforms_id) references platform (id);
alter table game_platforms add constraint FKi0s0wfmp3p34xfm3h9458cmcx foreign key (Game_id) references game (id);
alter table game_themes add constraint FKivce915we1ihempqv946jng1v foreign key (themes_id) references theme (id);
alter table game_themes add constraint FKo0td1ul31p4jopy8wtlbg5rhb foreign key (Game_id) references game (id);
