alter table game_companies drop foreign key FK6mp20inlbc6jc8axef8tupq41;
alter table game_companies drop foreign key FKl6bop2qxxfspoi00fd548hlk5;
alter table game_genres drop foreign key FKw91cn6ww8yw72nr59y28i8me;
alter table game_genres drop foreign key FK5tttono3swnbiopye7o19x0ur;
alter table game_platforms drop foreign key FKeqvfcfahkc1l3qnvpo78wjhsr;
alter table game_platforms drop foreign key FKi0s0wfmp3p34xfm3h9458cmcx;
alter table game_themes drop foreign key FKivce915we1ihempqv946jng1v;
alter table game_themes drop foreign key FKo0td1ul31p4jopy8wtlbg5rhb;
drop table if exists company;
drop table if exists game;
drop table if exists game_companies;
drop table if exists game_genres;
drop table if exists game_platforms;
drop table if exists game_themes;
drop table if exists genre;
drop table if exists platform;
drop table if exists theme;
alter table game_companies drop foreign key FK6mp20inlbc6jc8axef8tupq41;
alter table game_companies drop foreign key FKl6bop2qxxfspoi00fd548hlk5;
alter table game_genres drop foreign key FKw91cn6ww8yw72nr59y28i8me;
alter table game_genres drop foreign key FK5tttono3swnbiopye7o19x0ur;
alter table game_platforms drop foreign key FKeqvfcfahkc1l3qnvpo78wjhsr;
alter table game_platforms drop foreign key FKi0s0wfmp3p34xfm3h9458cmcx;
alter table game_themes drop foreign key FKivce915we1ihempqv946jng1v;
alter table game_themes drop foreign key FKo0td1ul31p4jopy8wtlbg5rhb;
drop table if exists company;
drop table if exists game;
drop table if exists game_companies;
drop table if exists game_genres;
drop table if exists game_platforms;
drop table if exists game_themes;
drop table if exists genre;
drop table if exists platform;
drop table if exists theme;
